# Data Schema Configuration
columns:
  LIMIT_BAL:
    type: int64
    description: "Credit limit"
    min_value: 10000
    max_value: 1000000

  SEX:
    type: int64
    description: "Gender (1=male, 2=female)"
    allowed_values: [1, 2]

  EDUCATION:
    type: int64
    description: "Education level"
    allowed_values: [0, 1, 2, 3, 4, 5, 6]

  MARRIAGE:
    type: int64
    description: "Marital status"
    allowed_values: [0,1, 2, 3]

  AGE:
    type: int64
    description: "Age in years"
    min_value: 18
    max_value: 100

  PAY_0:
    type: int64
    description: "Payment status in September"
    min_value: -2
    max_value: 8

  PAY_2:
    type: int64
    description: "Payment status in August"
    min_value: -2
    max_value: 8

  PAY_3:
    type: int64
    description: "Payment status in July"
    min_value: -2
    max_value: 8

  PAY_4:
    type: int64
    description: "Payment status in June"
    min_value: -2
    max_value: 8

  PAY_5:
    type: int64
    description: "Payment status in May"
    min_value: -2
    max_value: 8

  PAY_6:
    type: int64
    description: "Payment status in April"
    min_value: -2
    max_value: 8

  BILL_AMT1:
    type: float64
    description: "Bill amount in September"
    min_value: -165580
    max_value: 964511

  BILL_AMT2:
    type: float64
    description: "Bill amount in August"
    min_value: -69777
    max_value: 983931

  BILL_AMT3:
    type: float64
    description: "Bill amount in July"
    min_value: -157264
    max_value: 1664089

  BILL_AMT4:
    type: float64
    description: "Bill amount in June"
    min_value: -170000
    max_value: 891586

  BILL_AMT5:
    type: float64
    description: "Bill amount in May"
    min_value: -81334
    max_value: 927171

  BILL_AMT6:
    type: float64
    description: "Bill amount in April"
    min_value: -339603
    max_value: 961664

  PAY_AMT1:
    type: float64
    description: "Payment amount in September"
    min_value: 0
    max_value: 873552

  PAY_AMT2:
    type: float64
    description: "Payment amount in August"
    min_value: 0
    max_value: 1684259

  PAY_AMT3:
    type: float64
    description: "Payment amount in July"
    min_value: 0
    max_value: 896040

  PAY_AMT4:
    type: float64
    description: "Payment amount in June"
    min_value: 0
    max_value: 621000

  PAY_AMT5:
    type: float64
    description: "Payment amount in May"
    min_value: 0
    max_value: 426529

  PAY_AMT6:
    type: float64
    description: "Payment amount in April"
    min_value: 0
    max_value: 528666

target:
  column: "default.payment.next.month"
  type: int64
  description: "Default payment next month (1=yes, 0=no)"
  allowed_values: [0, 1]

# Data quality thresholds
data_quality:
  max_missing_percentage: 5.0
  max_duplicate_percentage: 1.0
  drift_threshold: 0.1
  outlier_threshold: 3.0